name: fact
channels:
  - defaults
  - pytorch
  - anaconda
  - conda-forge
  - nvidia
dependencies:
  - pip=23.3.1
  - pytorch=2.1.2
  - numpy=1.26.3
  - torchvision=0.16.2
  - scikit-learn=1.3.0
  - tqdm=4.66.1
  - pandas=2.1.4
  - pytorchcv=0.0.67
  - openai-clip=1.0.1
  - gdown=4.7.1
  - kaggle=1.6.3
  - nltk=3.8.1

  # extra AudioCLIP dependencies
  - librosa==0.10.1
  - termcolor==2.4.0
  - visdom==0.2.4
  - pytorch-ignite==0.4.8
