seed_everything: 42
model:
  n_concepts: 170
  n_classes: 5
  lam: 5
  alpha: 0.99
  max_iter: 10000
data:
  projector: 
    class_path: data.metashift.NNProjector
    init_args: 
      concept_bank_path: artifacts/outdir/broden_clip_RN50_0.01_50.pkl
      backbone:
        class_path: models.clip_encoder.CLIPImageEncoder
        init_args:
          model_name: RN50
  preprocessor_name: CLIP_RESNET50
